# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in oddsportal_scraper.gemspec
gemspec

gem 'rake', '~> 13.0'

gem 'rspec', '~> 3.0'

gem 'pry'

gem 'wombat', '~> 3.0.0'
