require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.1
  Exclude:
  - "**/scripts/**/**/**/*"
  - "vendor/**/*"
  - "**/tmp/**/*"
  - "**/db/data/**/*"
  - "**/db/data_schema.rb"
  - "**/db/schema.rb"
  - "**/bin/**/*"
  - "**/node_modules/**/*"

Layout/LineLength:
  Enabled: true
  Max: 120
  Exclude:
    - "config/**/*"
Metrics/BlockLength:
  Exclude:
    - "app/admin/**/*"
    - "config/**/*"
    - "spec/**/*"
Style/Encoding:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/KeywordParametersOrder:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: arguments
Rails/SkipsModelValidations:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/RakeEnvironment:
  Enabled: false
Rails/ReversibleMigration:
  Enabled: false
Rails/NotNullColumn:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Rails/FindById:
  Enabled: false
Layout/SpaceBeforeBrackets:
  Enabled: false
Lint/EmptyBlock:
  Enabled: false
Lint/ToEnumArguments:
  Enabled: false
Rails/Inquiry:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: arguments
Layout/EmptyLinesAroundClassBody:
  Description: Keeps track of empty lines around class bodies.
  Enabled: true
  EnforcedStyle: empty_lines
  SupportedStyles:
  - empty_lines
  - no_empty_lines
Lint:
  Exclude:
  - "**/db/migrate/**/*.rb"
Layout:
  Exclude:
  - "**/db/migrate/**/*.rb"
Style:
  Exclude:
  - "**/db/migrate/**/*.rb"
Naming/VariableNumber:
  EnforcedStyle: snake_case
Metrics/MethodLength:
  Exclude:
    - "lib/tasks/**/*.rake"
    - "**/db/migrate/**/*.rb"
Metrics/AbcSize:
  Exclude:
    - "lib/tasks/**/*.rake"
Naming/ConstantName:
  Exclude:
    - "lib/types/**/*.rb"

# RSpec
Layout/MultilineMethodCallIndentation:
  Include:
    - "spec/**/*_spec.rb"
  EnforcedStyle: indented
RSpec/ExampleLength:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 12
RSpec/FilePath:
  SpecSuffixOnly: true
RSpec/NestedGroups:
  Enabled: false
# RSpec styles from new Rubocop Versions
RSpec/BeNil: # new in 2.9.0
  Enabled: true
RSpec/ChangeByZero: # new in 2.11
  Enabled: true
RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: true
RSpec/SubjectDeclaration: # new in 2.5
  Enabled: true
RSpec/FactoryBot/SyntaxMethods: # new in 2.7
  Enabled: true
RSpec/Rails/AvoidSetupHook: # new in 2.4
  Enabled: true
RSpec/Rails/HaveHttpStatus: # new in 2.12
  Enabled: true
RSpec/BeEq: # new in 2.9.0
  Enabled: true
RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: true

# Styles from new Rubocop Versions
Rails/NegateInclude: # new in 2.7
  Enabled: true
Gemspec/DeprecatedAttributeAssignment: # new in 1.30
  Enabled: true
Lint/AmbiguousAssignment: # new in 1.7
  Enabled: true
Lint/DuplicateMagicComment: # new in 1.37
  Enabled: true
Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: true
Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: true
Lint/RequireRangeParentheses: # new in 1.32
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: true
Style/CollectionCompact: # new in 1.2
  Enabled: true
Style/FetchEnvVar: # new in 1.28
  Enabled: true
Style/RedundantInitialize: # new in 1.27
  Enabled: true
Style/MultilineInPatternThen: # new in 1.16
  Enabled: true
Style/NegatedIfElseCondition: # new in 1.2
  Enabled: true
Style/NumberedParameters: # new in 1.22
  Enabled: true
Style/HashSyntax:
  Enabled: false

# Rails styles from new Rubocop Version
Rails/WhereMissing: # new in 2.16
  Enabled: true
Rails/MigrationClassName: # new in 2.14
  Enabled: true
Rails/AddColumnIndex: # new in 2.11
  Enabled: true
Rails/FreezeTime: # new in 2.16
  Enabled: true
