require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.1
  Exclude:
  - "**/scripts/**/**/**/*"
  - "vendor/**/*"
  - "**/tmp/**/*"
  - "**/db/data/**/*"
  - "**/db/data_schema.rb"
  - "**/db/schema.rb"
  - "**/bin/**/*"
  - "**/node_modules/**/*"

Layout/LineLength:
  Enabled: true
  Max: 120
  Exclude:
    - "config/**/*"
Metrics/BlockLength:
  Exclude:
    - "app/admin/**/*"
    - "config/**/*"
    - "spec/**/*"
Style/Encoding:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/KeywordParametersOrder:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: arguments
Rails/SkipsModelValidations:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/RakeEnvironment:
  Enabled: false
Rails/ReversibleMigration:
  Enabled: false
Rails/NotNullColumn:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Rails/FindById:
  Enabled: false
Layout/SpaceBeforeBrackets:
  Enabled: false
Lint/EmptyBlock:
  Enabled: false
Lint/ToEnumArguments:
  Enabled: false
Rails/Inquiry:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: arguments
Layout/EmptyLinesAroundClassBody:
  Description: Keeps track of empty lines around class bodies.
  Enabled: true
  EnforcedStyle: empty_lines
  SupportedStyles:
  - empty_lines
  - no_empty_lines
Lint:
  Exclude:
  - "**/db/migrate/**/*.rb"
Layout:
  Exclude:
  - "**/db/migrate/**/*.rb"
Style:
  Exclude:
  - "**/db/migrate/**/*.rb"

# RSpec
Layout/MultilineMethodCallIndentation:
  Include:
    - "spec/**/*_spec.rb"
  EnforcedStyle: indented
RSpec/ExampleLength:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false

# Styles from new Rubocop Versions
Rails/NegateInclude: # new in 2.7
  Enabled: true
