services:
  mysql26:
    image: mysql:26.7.0
    container_name: mysql26
    environment:
      MYSQL_TCP_PORT: 3307
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3307"
    expose:
      - 3307
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --protocol=tcp --host=127.0.0.1 --port=3307 --user=root --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - mysql26:/var/lib/mysql
  redis8:
    image: redis:8.8.1
    container_name: redis8
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - redis8:/data

volumes:
  mysql26:
    driver: local
  redis8:
    driver: local
